// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pkg/bridge/bridge.proto

package bridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeamServerBridgeService_StageBeacon_FullMethodName             = "/bridge.TeamServerBridgeService/StageBeacon"
	TeamServerBridgeService_CheckInBeacon_FullMethodName           = "/bridge.TeamServerBridgeService/CheckInBeacon"
	TeamServerBridgeService_PushBeaconOutput_FullMethodName        = "/bridge.TeamServerBridgeService/PushBeaconOutput"
	TeamServerBridgeService_GetListenerSharedSecret_FullMethodName = "/bridge.TeamServerBridgeService/GetListenerSharedSecret"
	TeamServerBridgeService_GetBeaconSessionKey_FullMethodName     = "/bridge.TeamServerBridgeService/GetBeaconSessionKey"
	TeamServerBridgeService_LogListenerEvent_FullMethodName        = "/bridge.TeamServerBridgeService/LogListenerEvent"
	TeamServerBridgeService_GetBeaconConfig_FullMethodName         = "/bridge.TeamServerBridgeService/GetBeaconConfig"
	TeamServerBridgeService_GetTaskedFileChunk_FullMethodName      = "/bridge.TeamServerBridgeService/GetTaskedFileChunk"
	TeamServerBridgeService_ListenerControl_FullMethodName         = "/bridge.TeamServerBridgeService/ListenerControl"
)

// TeamServerBridgeServiceClient is the client API for TeamServerBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TeamServer 暴露给 Listener Service 的 gRPC 服务
type TeamServerBridgeServiceClient interface {
	// 处理新 Beacon 的注册请求
	StageBeacon(ctx context.Context, in *StageBeaconRequest, opts ...grpc.CallOption) (*StageBeaconResponse, error)
	// 处理已知 Beacon 的心跳并获取任务
	CheckInBeacon(ctx context.Context, in *CheckInBeaconRequest, opts ...grpc.CallOption) (*CheckInBeaconResponse, error)
	// 提交 Beacon 的任务执行结果
	PushBeaconOutput(ctx context.Context, in *PushBeaconOutputRequest, opts ...grpc.CallOption) (*PushBeaconOutputResponse, error)
	// 获取 Listener 的预设共享密钥
	GetListenerSharedSecret(ctx context.Context, in *GetListenerSharedSecretRequest, opts ...grpc.CallOption) (*GetListenerSharedSecretResponse, error)
	// 获取 Beacon 的会话密钥
	GetBeaconSessionKey(ctx context.Context, in *GetBeaconSessionKeyRequest, opts ...grpc.CallOption) (*GetBeaconSessionKeyResponse, error)
	// 记录 Listener 事件日志
	LogListenerEvent(ctx context.Context, in *LogListenerEventRequest, opts ...grpc.CallOption) (*LogListenerEventResponse, error)
	// 获取用于生成 Beacon 的配置
	GetBeaconConfig(ctx context.Context, in *GetBeaconConfigRequest, opts ...grpc.CallOption) (*GetBeaconConfigResponse, error)
	// 获取已分配任务的文件分片
	GetTaskedFileChunk(ctx context.Context, in *GetTaskedFileChunkRequest, opts ...grpc.CallOption) (*GetTaskedFileChunkResponse, error)
	// 新增：监听器控制流
	ListenerControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ListenerStatus, ListenerCommand], error)
}

type teamServerBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamServerBridgeServiceClient(cc grpc.ClientConnInterface) TeamServerBridgeServiceClient {
	return &teamServerBridgeServiceClient{cc}
}

func (c *teamServerBridgeServiceClient) StageBeacon(ctx context.Context, in *StageBeaconRequest, opts ...grpc.CallOption) (*StageBeaconResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageBeaconResponse)
	err := c.cc.Invoke(ctx, TeamServerBridgeService_StageBeacon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServerBridgeServiceClient) CheckInBeacon(ctx context.Context, in *CheckInBeaconRequest, opts ...grpc.CallOption) (*CheckInBeaconResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInBeaconResponse)
	err := c.cc.Invoke(ctx, TeamServerBridgeService_CheckInBeacon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServerBridgeServiceClient) PushBeaconOutput(ctx context.Context, in *PushBeaconOutputRequest, opts ...grpc.CallOption) (*PushBeaconOutputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushBeaconOutputResponse)
	err := c.cc.Invoke(ctx, TeamServerBridgeService_PushBeaconOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServerBridgeServiceClient) GetListenerSharedSecret(ctx context.Context, in *GetListenerSharedSecretRequest, opts ...grpc.CallOption) (*GetListenerSharedSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListenerSharedSecretResponse)
	err := c.cc.Invoke(ctx, TeamServerBridgeService_GetListenerSharedSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServerBridgeServiceClient) GetBeaconSessionKey(ctx context.Context, in *GetBeaconSessionKeyRequest, opts ...grpc.CallOption) (*GetBeaconSessionKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBeaconSessionKeyResponse)
	err := c.cc.Invoke(ctx, TeamServerBridgeService_GetBeaconSessionKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServerBridgeServiceClient) LogListenerEvent(ctx context.Context, in *LogListenerEventRequest, opts ...grpc.CallOption) (*LogListenerEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogListenerEventResponse)
	err := c.cc.Invoke(ctx, TeamServerBridgeService_LogListenerEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServerBridgeServiceClient) GetBeaconConfig(ctx context.Context, in *GetBeaconConfigRequest, opts ...grpc.CallOption) (*GetBeaconConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBeaconConfigResponse)
	err := c.cc.Invoke(ctx, TeamServerBridgeService_GetBeaconConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServerBridgeServiceClient) GetTaskedFileChunk(ctx context.Context, in *GetTaskedFileChunkRequest, opts ...grpc.CallOption) (*GetTaskedFileChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskedFileChunkResponse)
	err := c.cc.Invoke(ctx, TeamServerBridgeService_GetTaskedFileChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServerBridgeServiceClient) ListenerControl(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ListenerStatus, ListenerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TeamServerBridgeService_ServiceDesc.Streams[0], TeamServerBridgeService_ListenerControl_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenerStatus, ListenerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamServerBridgeService_ListenerControlClient = grpc.BidiStreamingClient[ListenerStatus, ListenerCommand]

// TeamServerBridgeServiceServer is the server API for TeamServerBridgeService service.
// All implementations must embed UnimplementedTeamServerBridgeServiceServer
// for forward compatibility.
//
// TeamServer 暴露给 Listener Service 的 gRPC 服务
type TeamServerBridgeServiceServer interface {
	// 处理新 Beacon 的注册请求
	StageBeacon(context.Context, *StageBeaconRequest) (*StageBeaconResponse, error)
	// 处理已知 Beacon 的心跳并获取任务
	CheckInBeacon(context.Context, *CheckInBeaconRequest) (*CheckInBeaconResponse, error)
	// 提交 Beacon 的任务执行结果
	PushBeaconOutput(context.Context, *PushBeaconOutputRequest) (*PushBeaconOutputResponse, error)
	// 获取 Listener 的预设共享密钥
	GetListenerSharedSecret(context.Context, *GetListenerSharedSecretRequest) (*GetListenerSharedSecretResponse, error)
	// 获取 Beacon 的会话密钥
	GetBeaconSessionKey(context.Context, *GetBeaconSessionKeyRequest) (*GetBeaconSessionKeyResponse, error)
	// 记录 Listener 事件日志
	LogListenerEvent(context.Context, *LogListenerEventRequest) (*LogListenerEventResponse, error)
	// 获取用于生成 Beacon 的配置
	GetBeaconConfig(context.Context, *GetBeaconConfigRequest) (*GetBeaconConfigResponse, error)
	// 获取已分配任务的文件分片
	GetTaskedFileChunk(context.Context, *GetTaskedFileChunkRequest) (*GetTaskedFileChunkResponse, error)
	// 新增：监听器控制流
	ListenerControl(grpc.BidiStreamingServer[ListenerStatus, ListenerCommand]) error
	mustEmbedUnimplementedTeamServerBridgeServiceServer()
}

// UnimplementedTeamServerBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeamServerBridgeServiceServer struct{}

func (UnimplementedTeamServerBridgeServiceServer) StageBeacon(context.Context, *StageBeaconRequest) (*StageBeaconResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StageBeacon not implemented")
}
func (UnimplementedTeamServerBridgeServiceServer) CheckInBeacon(context.Context, *CheckInBeaconRequest) (*CheckInBeaconResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckInBeacon not implemented")
}
func (UnimplementedTeamServerBridgeServiceServer) PushBeaconOutput(context.Context, *PushBeaconOutputRequest) (*PushBeaconOutputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushBeaconOutput not implemented")
}
func (UnimplementedTeamServerBridgeServiceServer) GetListenerSharedSecret(context.Context, *GetListenerSharedSecretRequest) (*GetListenerSharedSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListenerSharedSecret not implemented")
}
func (UnimplementedTeamServerBridgeServiceServer) GetBeaconSessionKey(context.Context, *GetBeaconSessionKeyRequest) (*GetBeaconSessionKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBeaconSessionKey not implemented")
}
func (UnimplementedTeamServerBridgeServiceServer) LogListenerEvent(context.Context, *LogListenerEventRequest) (*LogListenerEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogListenerEvent not implemented")
}
func (UnimplementedTeamServerBridgeServiceServer) GetBeaconConfig(context.Context, *GetBeaconConfigRequest) (*GetBeaconConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBeaconConfig not implemented")
}
func (UnimplementedTeamServerBridgeServiceServer) GetTaskedFileChunk(context.Context, *GetTaskedFileChunkRequest) (*GetTaskedFileChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskedFileChunk not implemented")
}
func (UnimplementedTeamServerBridgeServiceServer) ListenerControl(grpc.BidiStreamingServer[ListenerStatus, ListenerCommand]) error {
	return status.Error(codes.Unimplemented, "method ListenerControl not implemented")
}
func (UnimplementedTeamServerBridgeServiceServer) mustEmbedUnimplementedTeamServerBridgeServiceServer() {
}
func (UnimplementedTeamServerBridgeServiceServer) testEmbeddedByValue() {}

// UnsafeTeamServerBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeamServerBridgeServiceServer will
// result in compilation errors.
type UnsafeTeamServerBridgeServiceServer interface {
	mustEmbedUnimplementedTeamServerBridgeServiceServer()
}

func RegisterTeamServerBridgeServiceServer(s grpc.ServiceRegistrar, srv TeamServerBridgeServiceServer) {
	// If the following call panics, it indicates UnimplementedTeamServerBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeamServerBridgeService_ServiceDesc, srv)
}

func _TeamServerBridgeService_StageBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageBeaconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServerBridgeServiceServer).StageBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServerBridgeService_StageBeacon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServerBridgeServiceServer).StageBeacon(ctx, req.(*StageBeaconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamServerBridgeService_CheckInBeacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInBeaconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServerBridgeServiceServer).CheckInBeacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServerBridgeService_CheckInBeacon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServerBridgeServiceServer).CheckInBeacon(ctx, req.(*CheckInBeaconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamServerBridgeService_PushBeaconOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushBeaconOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServerBridgeServiceServer).PushBeaconOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServerBridgeService_PushBeaconOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServerBridgeServiceServer).PushBeaconOutput(ctx, req.(*PushBeaconOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamServerBridgeService_GetListenerSharedSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListenerSharedSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServerBridgeServiceServer).GetListenerSharedSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServerBridgeService_GetListenerSharedSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServerBridgeServiceServer).GetListenerSharedSecret(ctx, req.(*GetListenerSharedSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamServerBridgeService_GetBeaconSessionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeaconSessionKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServerBridgeServiceServer).GetBeaconSessionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServerBridgeService_GetBeaconSessionKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServerBridgeServiceServer).GetBeaconSessionKey(ctx, req.(*GetBeaconSessionKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamServerBridgeService_LogListenerEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogListenerEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServerBridgeServiceServer).LogListenerEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServerBridgeService_LogListenerEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServerBridgeServiceServer).LogListenerEvent(ctx, req.(*LogListenerEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamServerBridgeService_GetBeaconConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeaconConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServerBridgeServiceServer).GetBeaconConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServerBridgeService_GetBeaconConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServerBridgeServiceServer).GetBeaconConfig(ctx, req.(*GetBeaconConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamServerBridgeService_GetTaskedFileChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskedFileChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServerBridgeServiceServer).GetTaskedFileChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamServerBridgeService_GetTaskedFileChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServerBridgeServiceServer).GetTaskedFileChunk(ctx, req.(*GetTaskedFileChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamServerBridgeService_ListenerControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeamServerBridgeServiceServer).ListenerControl(&grpc.GenericServerStream[ListenerStatus, ListenerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TeamServerBridgeService_ListenerControlServer = grpc.BidiStreamingServer[ListenerStatus, ListenerCommand]

// TeamServerBridgeService_ServiceDesc is the grpc.ServiceDesc for TeamServerBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeamServerBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bridge.TeamServerBridgeService",
	HandlerType: (*TeamServerBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StageBeacon",
			Handler:    _TeamServerBridgeService_StageBeacon_Handler,
		},
		{
			MethodName: "CheckInBeacon",
			Handler:    _TeamServerBridgeService_CheckInBeacon_Handler,
		},
		{
			MethodName: "PushBeaconOutput",
			Handler:    _TeamServerBridgeService_PushBeaconOutput_Handler,
		},
		{
			MethodName: "GetListenerSharedSecret",
			Handler:    _TeamServerBridgeService_GetListenerSharedSecret_Handler,
		},
		{
			MethodName: "GetBeaconSessionKey",
			Handler:    _TeamServerBridgeService_GetBeaconSessionKey_Handler,
		},
		{
			MethodName: "LogListenerEvent",
			Handler:    _TeamServerBridgeService_LogListenerEvent_Handler,
		},
		{
			MethodName: "GetBeaconConfig",
			Handler:    _TeamServerBridgeService_GetBeaconConfig_Handler,
		},
		{
			MethodName: "GetTaskedFileChunk",
			Handler:    _TeamServerBridgeService_GetTaskedFileChunk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenerControl",
			Handler:       _TeamServerBridgeService_ListenerControl_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/bridge/bridge.proto",
}
