// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pkg/bridge/bridge.proto

package bridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenerCommand_Action int32

const (
	ListenerCommand_START         ListenerCommand_Action = 0
	ListenerCommand_STOP          ListenerCommand_Action = 1
	ListenerCommand_RESTART       ListenerCommand_Action = 2
	ListenerCommand_UPDATE_CONFIG ListenerCommand_Action = 3 // 热更新配置
	ListenerCommand_EXIT          ListenerCommand_Action = 4 // 进程退出
)

// Enum value maps for ListenerCommand_Action.
var (
	ListenerCommand_Action_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "RESTART",
		3: "UPDATE_CONFIG",
		4: "EXIT",
	}
	ListenerCommand_Action_value = map[string]int32{
		"START":         0,
		"STOP":          1,
		"RESTART":       2,
		"UPDATE_CONFIG": 3,
		"EXIT":          4,
	}
)

func (x ListenerCommand_Action) Enum() *ListenerCommand_Action {
	p := new(ListenerCommand_Action)
	*p = x
	return p
}

func (x ListenerCommand_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenerCommand_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_bridge_bridge_proto_enumTypes[0].Descriptor()
}

func (ListenerCommand_Action) Type() protoreflect.EnumType {
	return &file_pkg_bridge_bridge_proto_enumTypes[0]
}

func (x ListenerCommand_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenerCommand_Action.Descriptor instead.
func (ListenerCommand_Action) EnumDescriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{1, 0}
}

type TunnelMessage_CommandType int32

const (
	TunnelMessage_START TunnelMessage_CommandType = 0
	TunnelMessage_DATA  TunnelMessage_CommandType = 1
	TunnelMessage_STOP  TunnelMessage_CommandType = 2
)

// Enum value maps for TunnelMessage_CommandType.
var (
	TunnelMessage_CommandType_name = map[int32]string{
		0: "START",
		1: "DATA",
		2: "STOP",
	}
	TunnelMessage_CommandType_value = map[string]int32{
		"START": 0,
		"DATA":  1,
		"STOP":  2,
	}
)

func (x TunnelMessage_CommandType) Enum() *TunnelMessage_CommandType {
	p := new(TunnelMessage_CommandType)
	*p = x
	return p
}

func (x TunnelMessage_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelMessage_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_bridge_bridge_proto_enumTypes[1].Descriptor()
}

func (TunnelMessage_CommandType) Type() protoreflect.EnumType {
	return &file_pkg_bridge_bridge_proto_enumTypes[1]
}

func (x TunnelMessage_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelMessage_CommandType.Descriptor instead.
func (TunnelMessage_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{20, 0}
}

// Listener 上报的状态
type ListenerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenerName  string                 `protobuf:"bytes,1,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`                                    // 当前是否在监听
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`     // 如果出错，通过这里上报
	ActiveBeacons int32                  `protobuf:"varint,4,opt,name=active_beacons,json=activeBeacons,proto3" json:"active_beacons,omitempty"` // 当前连接的 Beacon 数量（用于监控面板）
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                         // Listener 类型 (e.g. "HTTP")
	ConfigJson    string                 `protobuf:"bytes,6,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`           // 当前配置快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerStatus) Reset() {
	*x = ListenerStatus{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerStatus) ProtoMessage() {}

func (x *ListenerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerStatus.ProtoReflect.Descriptor instead.
func (*ListenerStatus) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *ListenerStatus) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

func (x *ListenerStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ListenerStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ListenerStatus) GetActiveBeacons() int32 {
	if x != nil {
		return x.ActiveBeacons
	}
	return 0
}

func (x *ListenerStatus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListenerStatus) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// TS 下发的指令
type ListenerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Action        ListenerCommand_Action `protobuf:"varint,2,opt,name=action,proto3,enum=bridge.ListenerCommand_Action" json:"action,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // 如果是更新配置，携带新配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerCommand) Reset() {
	*x = ListenerCommand{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerCommand) ProtoMessage() {}

func (x *ListenerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerCommand.ProtoReflect.Descriptor instead.
func (*ListenerCommand) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *ListenerCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListenerCommand) GetAction() ListenerCommand_Action {
	if x != nil {
		return x.Action
	}
	return ListenerCommand_START
}

func (x *ListenerCommand) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// Beacon 的核心元数据
type BeaconMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BeaconId        string                 `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`                         // Beacon 自身的 UUID 或唯一标识符
	Pid             int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`                                                  // 进程 ID
	Os              string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`                                                     // 操作系统类型 (e.g., "windows", "linux", "darwin")
	Arch            string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`                                                 // CPU 架构 (e.g., "amd64", "arm64", "x86")
	Username        string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`                                         // 当前用户名
	Hostname        string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`                                         // 主机名
	InternalIp      string                 `protobuf:"bytes,7,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`                   // 内部 IP 地址
	ProcessName     string                 `protobuf:"bytes,8,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`                // Beacon 进程名
	IsHighIntegrity bool                   `protobuf:"varint,9,opt,name=is_high_integrity,json=isHighIntegrity,proto3" json:"is_high_integrity,omitempty"` // 是否在高权限下运行
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BeaconMetadata) Reset() {
	*x = BeaconMetadata{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconMetadata) ProtoMessage() {}

func (x *BeaconMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconMetadata.ProtoReflect.Descriptor instead.
func (*BeaconMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *BeaconMetadata) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *BeaconMetadata) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *BeaconMetadata) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *BeaconMetadata) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *BeaconMetadata) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BeaconMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *BeaconMetadata) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *BeaconMetadata) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *BeaconMetadata) GetIsHighIntegrity() bool {
	if x != nil {
		return x.IsHighIntegrity
	}
	return false
}

// Staging 请求
type StageBeaconRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenerName  string                 `protobuf:"bytes,1,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"` // 处理此请求的 Listener 实例名
	RemoteAddr    string                 `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`       // Beacon 的来源网络地址
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // Listener 接收到请求的时间戳
	Metadata      *BeaconMetadata        `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`                             // Listener 解析后的 Beacon 元数据
	PublicKey     []byte                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`          // 可选: Beacon 的公钥，用于加密 SessionKey
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageBeaconRequest) Reset() {
	*x = StageBeaconRequest{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageBeaconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageBeaconRequest) ProtoMessage() {}

func (x *StageBeaconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageBeaconRequest.ProtoReflect.Descriptor instead.
func (*StageBeaconRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *StageBeaconRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

func (x *StageBeaconRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *StageBeaconRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StageBeaconRequest) GetMetadata() *BeaconMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StageBeaconRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// Staging 响应
type StageBeaconResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AssignedBeaconId    string                 `protobuf:"bytes,1,opt,name=assigned_beacon_id,json=assignedBeaconId,proto3" json:"assigned_beacon_id,omitempty"`           // TeamServer 确认或分配的 ID
	SessionKey          []byte                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`                               // 分配的会话密钥 (可能是原始密钥或用 PublicKey 加密后的)
	SessionKeyEncrypted bool                   `protobuf:"varint,3,opt,name=session_key_encrypted,json=sessionKeyEncrypted,proto3" json:"session_key_encrypted,omitempty"` // 指示 session_key 是否已被加密
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StageBeaconResponse) Reset() {
	*x = StageBeaconResponse{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageBeaconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageBeaconResponse) ProtoMessage() {}

func (x *StageBeaconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageBeaconResponse.ProtoReflect.Descriptor instead.
func (*StageBeaconResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *StageBeaconResponse) GetAssignedBeaconId() string {
	if x != nil {
		return x.AssignedBeaconId
	}
	return ""
}

func (x *StageBeaconResponse) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *StageBeaconResponse) GetSessionKeyEncrypted() bool {
	if x != nil {
		return x.SessionKeyEncrypted
	}
	return false
}

// CheckIn 请求
type CheckInBeaconRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BeaconId           string                 `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`                                 // 进行心跳的 Beacon ID
	ListenerName       string                 `protobuf:"bytes,2,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`                     // 处理此请求的 Listener 实例名
	RemoteAddr         string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`                           // Beacon 的来源网络地址
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                               // Listener 接收到请求的时间戳
	OutgoingTunnelData []*TunnelMessage       `protobuf:"bytes,5,rep,name=outgoing_tunnel_data,json=outgoingTunnelData,proto3" json:"outgoing_tunnel_data,omitempty"` // Agent发送给TeamServer的隧道数据
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckInBeaconRequest) Reset() {
	*x = CheckInBeaconRequest{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInBeaconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInBeaconRequest) ProtoMessage() {}

func (x *CheckInBeaconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInBeaconRequest.ProtoReflect.Descriptor instead.
func (*CheckInBeaconRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *CheckInBeaconRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *CheckInBeaconRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

func (x *CheckInBeaconRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *CheckInBeaconRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CheckInBeaconRequest) GetOutgoingTunnelData() []*TunnelMessage {
	if x != nil {
		return x.OutgoingTunnelData
	}
	return nil
}

// Task 结构定义
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`           // TeamServer 分配的任务唯一 ID
	CommandId     uint32                 `protobuf:"varint,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // 指令的操作码
	Arguments     []byte                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`                   // 原始未加密参数 (TeamServer 内部格式)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *Task) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// CheckIn 响应
type CheckInBeaconResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Tasks              []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`                                                       // 原始未加密任务对象列表
	NewSleep           int32                  `protobuf:"varint,2,opt,name=new_sleep,json=newSleep,proto3" json:"new_sleep,omitempty"`                                // 可选: 新的 sleep 时间 (秒)
	IncomingTunnelData []*TunnelMessage       `protobuf:"bytes,3,rep,name=incoming_tunnel_data,json=incomingTunnelData,proto3" json:"incoming_tunnel_data,omitempty"` // TeamServer发送给Agent的隧道数据
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckInBeaconResponse) Reset() {
	*x = CheckInBeaconResponse{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInBeaconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInBeaconResponse) ProtoMessage() {}

func (x *CheckInBeaconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInBeaconResponse.ProtoReflect.Descriptor instead.
func (*CheckInBeaconResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{7}
}

func (x *CheckInBeaconResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *CheckInBeaconResponse) GetNewSleep() int32 {
	if x != nil {
		return x.NewSleep
	}
	return 0
}

func (x *CheckInBeaconResponse) GetIncomingTunnelData() []*TunnelMessage {
	if x != nil {
		return x.IncomingTunnelData
	}
	return nil
}

// PushOutput 请求
type PushBeaconOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeaconId      string                 `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`             // 回传结果的 Beacon ID
	ListenerName  string                 `protobuf:"bytes,2,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"` // 处理此请求的 Listener 实例名
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`       // Beacon 的来源网络地址
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // Listener 接收到请求的时间戳
	TaskId        string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                   // 此结果对应的任务 ID
	CommandId     uint32                 `protobuf:"varint,6,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`         // 执行的指令 ID
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                // 任务执行状态码 (0 代表成功)
	Output        []byte                 `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty"`                                 // **已由 Listener 解密** 的原始任务输出数据 (TeamServer 内部格式)
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 如果 status != 0，对应的错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBeaconOutputRequest) Reset() {
	*x = PushBeaconOutputRequest{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBeaconOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBeaconOutputRequest) ProtoMessage() {}

func (x *PushBeaconOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBeaconOutputRequest.ProtoReflect.Descriptor instead.
func (*PushBeaconOutputRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *PushBeaconOutputRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *PushBeaconOutputRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

func (x *PushBeaconOutputRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *PushBeaconOutputRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PushBeaconOutputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PushBeaconOutputRequest) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *PushBeaconOutputRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PushBeaconOutputRequest) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *PushBeaconOutputRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// PushOutput 响应
type PushBeaconOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBeaconOutputResponse) Reset() {
	*x = PushBeaconOutputResponse{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBeaconOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBeaconOutputResponse) ProtoMessage() {}

func (x *PushBeaconOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBeaconOutputResponse.ProtoReflect.Descriptor instead.
func (*PushBeaconOutputResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{9}
}

// 获取 Listener SharedSecret 请求
type GetListenerSharedSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenerName  string                 `protobuf:"bytes,1,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenerSharedSecretRequest) Reset() {
	*x = GetListenerSharedSecretRequest{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenerSharedSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerSharedSecretRequest) ProtoMessage() {}

func (x *GetListenerSharedSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerSharedSecretRequest.ProtoReflect.Descriptor instead.
func (*GetListenerSharedSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *GetListenerSharedSecretRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

// 获取 Listener SharedSecret 响应
type GetListenerSharedSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharedSecret  []byte                 `protobuf:"bytes,1,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenerSharedSecretResponse) Reset() {
	*x = GetListenerSharedSecretResponse{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenerSharedSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerSharedSecretResponse) ProtoMessage() {}

func (x *GetListenerSharedSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerSharedSecretResponse.ProtoReflect.Descriptor instead.
func (*GetListenerSharedSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *GetListenerSharedSecretResponse) GetSharedSecret() []byte {
	if x != nil {
		return x.SharedSecret
	}
	return nil
}

// 获取 Beacon SessionKey 请求
type GetBeaconSessionKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeaconId      string                 `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeaconSessionKeyRequest) Reset() {
	*x = GetBeaconSessionKeyRequest{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeaconSessionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeaconSessionKeyRequest) ProtoMessage() {}

func (x *GetBeaconSessionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeaconSessionKeyRequest.ProtoReflect.Descriptor instead.
func (*GetBeaconSessionKeyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *GetBeaconSessionKeyRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

// 获取 Beacon SessionKey 响应
type GetBeaconSessionKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    []byte                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"` // Beacon 是否存在且活动
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeaconSessionKeyResponse) Reset() {
	*x = GetBeaconSessionKeyResponse{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeaconSessionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeaconSessionKeyResponse) ProtoMessage() {}

func (x *GetBeaconSessionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeaconSessionKeyResponse.ProtoReflect.Descriptor instead.
func (*GetBeaconSessionKeyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{13}
}

func (x *GetBeaconSessionKeyResponse) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *GetBeaconSessionKeyResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// 记录 Listener 日志事件请求
type LogListenerEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenerName  string                 `protobuf:"bytes,1,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`                                                                             // 日志级别 ("INFO", "WARN", "ERROR", "DEBUG")
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                         // 日志消息
	Fields        map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 结构化日志字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogListenerEventRequest) Reset() {
	*x = LogListenerEventRequest{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogListenerEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogListenerEventRequest) ProtoMessage() {}

func (x *LogListenerEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogListenerEventRequest.ProtoReflect.Descriptor instead.
func (*LogListenerEventRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *LogListenerEventRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

func (x *LogListenerEventRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogListenerEventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogListenerEventRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 记录 Listener 日志事件响应
type LogListenerEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogListenerEventResponse) Reset() {
	*x = LogListenerEventResponse{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogListenerEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogListenerEventResponse) ProtoMessage() {}

func (x *LogListenerEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogListenerEventResponse.ProtoReflect.Descriptor instead.
func (*LogListenerEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{15}
}

// 获取 Beacon 配置请求
type GetBeaconConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenerName  string                 `protobuf:"bytes,1,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeaconConfigRequest) Reset() {
	*x = GetBeaconConfigRequest{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeaconConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeaconConfigRequest) ProtoMessage() {}

func (x *GetBeaconConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeaconConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBeaconConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *GetBeaconConfigRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

// 获取 Beacon 配置响应
type GetBeaconConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-Value 配置对 (例如回连地址, 端口等)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBeaconConfigResponse) Reset() {
	*x = GetBeaconConfigResponse{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBeaconConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeaconConfigResponse) ProtoMessage() {}

func (x *GetBeaconConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeaconConfigResponse.ProtoReflect.Descriptor instead.
func (*GetBeaconConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{17}
}

func (x *GetBeaconConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// 获取文件分片请求
type GetTaskedFileChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                 // 'download' 任务的 ID
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"` // 请求的分片序号 (从 0 开始)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskedFileChunkRequest) Reset() {
	*x = GetTaskedFileChunkRequest{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskedFileChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskedFileChunkRequest) ProtoMessage() {}

func (x *GetTaskedFileChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskedFileChunkRequest.ProtoReflect.Descriptor instead.
func (*GetTaskedFileChunkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{18}
}

func (x *GetTaskedFileChunkRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskedFileChunkRequest) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

// 获取文件分片响应
type GetTaskedFileChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"` // 分片的二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskedFileChunkResponse) Reset() {
	*x = GetTaskedFileChunkResponse{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskedFileChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskedFileChunkResponse) ProtoMessage() {}

func (x *GetTaskedFileChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskedFileChunkResponse.ProtoReflect.Descriptor instead.
func (*GetTaskedFileChunkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{19}
}

func (x *GetTaskedFileChunkResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

// TunnelMessage 隧道数据消息
type TunnelMessage struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TunnelId      string                    `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Data          []byte                    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsFin         bool                      `protobuf:"varint,3,opt,name=is_fin,json=isFin,proto3" json:"is_fin,omitempty"`         // End of stream/connection close
	IsError       bool                      `protobuf:"varint,4,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`   // Indicates an error occurred
	ErrorMsg      string                    `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"` // Error message
	Target        string                    `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`                     // Target address for TunnelCommandStart (only sent by TeamServer)
	CommandType   TunnelMessage_CommandType `protobuf:"varint,7,opt,name=command_type,json=commandType,proto3,enum=bridge.TunnelMessage_CommandType" json:"command_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_pkg_bridge_bridge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{20}
}

func (x *TunnelMessage) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *TunnelMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TunnelMessage) GetIsFin() bool {
	if x != nil {
		return x.IsFin
	}
	return false
}

func (x *TunnelMessage) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *TunnelMessage) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *TunnelMessage) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TunnelMessage) GetCommandType() TunnelMessage_CommandType {
	if x != nil {
		return x.CommandType
	}
	return TunnelMessage_START
}

var File_pkg_bridge_bridge_proto protoreflect.FileDescriptor

const file_pkg_bridge_bridge_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/bridge/bridge.proto\x12\x06bridge\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xce\x01\n" +
	"\x0eListenerStatus\x12#\n" +
	"\rlistener_name\x18\x01 \x01(\tR\flistenerName\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eactive_beacons\x18\x04 \x01(\x05R\ractiveBeacons\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1f\n" +
	"\vconfig_json\x18\x06 \x01(\tR\n" +
	"configJson\"\xd2\x01\n" +
	"\x0fListenerCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x126\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1e.bridge.ListenerCommand.ActionR\x06action\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\"G\n" +
	"\x06Action\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\v\n" +
	"\aRESTART\x10\x02\x12\x11\n" +
	"\rUPDATE_CONFIG\x10\x03\x12\b\n" +
	"\x04EXIT\x10\x04\"\x8b\x02\n" +
	"\x0eBeaconMetadata\x12\x1b\n" +
	"\tbeacon_id\x18\x01 \x01(\tR\bbeaconId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12\x1f\n" +
	"\vinternal_ip\x18\a \x01(\tR\n" +
	"internalIp\x12!\n" +
	"\fprocess_name\x18\b \x01(\tR\vprocessName\x12*\n" +
	"\x11is_high_integrity\x18\t \x01(\bR\x0fisHighIntegrity\"\xe7\x01\n" +
	"\x12StageBeaconRequest\x12#\n" +
	"\rlistener_name\x18\x01 \x01(\tR\flistenerName\x12\x1f\n" +
	"\vremote_addr\x18\x02 \x01(\tR\n" +
	"remoteAddr\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x122\n" +
	"\bmetadata\x18\x04 \x01(\v2\x16.bridge.BeaconMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\"\x98\x01\n" +
	"\x13StageBeaconResponse\x12,\n" +
	"\x12assigned_beacon_id\x18\x01 \x01(\tR\x10assignedBeaconId\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\fR\n" +
	"sessionKey\x122\n" +
	"\x15session_key_encrypted\x18\x03 \x01(\bR\x13sessionKeyEncrypted\"\xfc\x01\n" +
	"\x14CheckInBeaconRequest\x12\x1b\n" +
	"\tbeacon_id\x18\x01 \x01(\tR\bbeaconId\x12#\n" +
	"\rlistener_name\x18\x02 \x01(\tR\flistenerName\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12G\n" +
	"\x14outgoing_tunnel_data\x18\x05 \x03(\v2\x15.bridge.TunnelMessageR\x12outgoingTunnelData\"\\\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\rR\tcommandId\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\fR\targuments\"\xa1\x01\n" +
	"\x15CheckInBeaconResponse\x12\"\n" +
	"\x05tasks\x18\x01 \x03(\v2\f.bridge.TaskR\x05tasks\x12\x1b\n" +
	"\tnew_sleep\x18\x02 \x01(\x05R\bnewSleep\x12G\n" +
	"\x14incoming_tunnel_data\x18\x03 \x03(\v2\x15.bridge.TunnelMessageR\x12incomingTunnelData\"\xc3\x02\n" +
	"\x17PushBeaconOutputRequest\x12\x1b\n" +
	"\tbeacon_id\x18\x01 \x01(\tR\bbeaconId\x12#\n" +
	"\rlistener_name\x18\x02 \x01(\tR\flistenerName\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x06 \x01(\rR\tcommandId\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x16\n" +
	"\x06output\x18\b \x01(\fR\x06output\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\"\x1a\n" +
	"\x18PushBeaconOutputResponse\"E\n" +
	"\x1eGetListenerSharedSecretRequest\x12#\n" +
	"\rlistener_name\x18\x01 \x01(\tR\flistenerName\"F\n" +
	"\x1fGetListenerSharedSecretResponse\x12#\n" +
	"\rshared_secret\x18\x01 \x01(\fR\fsharedSecret\"9\n" +
	"\x1aGetBeaconSessionKeyRequest\x12\x1b\n" +
	"\tbeacon_id\x18\x01 \x01(\tR\bbeaconId\"T\n" +
	"\x1bGetBeaconSessionKeyResponse\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\fR\n" +
	"sessionKey\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xee\x01\n" +
	"\x17LogListenerEventRequest\x12#\n" +
	"\rlistener_name\x18\x01 \x01(\tR\flistenerName\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12C\n" +
	"\x06fields\x18\x04 \x03(\v2+.bridge.LogListenerEventRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1a\n" +
	"\x18LogListenerEventResponse\"=\n" +
	"\x16GetBeaconConfigRequest\x12#\n" +
	"\rlistener_name\x18\x01 \x01(\tR\flistenerName\"\x99\x01\n" +
	"\x17GetBeaconConfigResponse\x12C\n" +
	"\x06config\x18\x01 \x03(\v2+.bridge.GetBeaconConfigResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x19GetTaskedFileChunkRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\";\n" +
	"\x1aGetTaskedFileChunkResponse\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\"\x9b\x02\n" +
	"\rTunnelMessage\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x15\n" +
	"\x06is_fin\x18\x03 \x01(\bR\x05isFin\x12\x19\n" +
	"\bis_error\x18\x04 \x01(\bR\aisError\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x12\x16\n" +
	"\x06target\x18\x06 \x01(\tR\x06target\x12D\n" +
	"\fcommand_type\x18\a \x01(\x0e2!.bridge.TunnelMessage.CommandTypeR\vcommandType\",\n" +
	"\vCommandType\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04DATA\x10\x01\x12\b\n" +
	"\x04STOP\x10\x022\xa2\x06\n" +
	"\x17TeamServerBridgeService\x12F\n" +
	"\vStageBeacon\x12\x1a.bridge.StageBeaconRequest\x1a\x1b.bridge.StageBeaconResponse\x12L\n" +
	"\rCheckInBeacon\x12\x1c.bridge.CheckInBeaconRequest\x1a\x1d.bridge.CheckInBeaconResponse\x12U\n" +
	"\x10PushBeaconOutput\x12\x1f.bridge.PushBeaconOutputRequest\x1a .bridge.PushBeaconOutputResponse\x12j\n" +
	"\x17GetListenerSharedSecret\x12&.bridge.GetListenerSharedSecretRequest\x1a'.bridge.GetListenerSharedSecretResponse\x12^\n" +
	"\x13GetBeaconSessionKey\x12\".bridge.GetBeaconSessionKeyRequest\x1a#.bridge.GetBeaconSessionKeyResponse\x12U\n" +
	"\x10LogListenerEvent\x12\x1f.bridge.LogListenerEventRequest\x1a .bridge.LogListenerEventResponse\x12R\n" +
	"\x0fGetBeaconConfig\x12\x1e.bridge.GetBeaconConfigRequest\x1a\x1f.bridge.GetBeaconConfigResponse\x12[\n" +
	"\x12GetTaskedFileChunk\x12!.bridge.GetTaskedFileChunkRequest\x1a\".bridge.GetTaskedFileChunkResponse\x12F\n" +
	"\x0fListenerControl\x12\x16.bridge.ListenerStatus\x1a\x17.bridge.ListenerCommand(\x010\x01B\x15Z\x13simplec2/pkg/bridgeb\x06proto3"

var (
	file_pkg_bridge_bridge_proto_rawDescOnce sync.Once
	file_pkg_bridge_bridge_proto_rawDescData []byte
)

func file_pkg_bridge_bridge_proto_rawDescGZIP() []byte {
	file_pkg_bridge_bridge_proto_rawDescOnce.Do(func() {
		file_pkg_bridge_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_bridge_bridge_proto_rawDesc), len(file_pkg_bridge_bridge_proto_rawDesc)))
	})
	return file_pkg_bridge_bridge_proto_rawDescData
}

var file_pkg_bridge_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_bridge_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_pkg_bridge_bridge_proto_goTypes = []any{
	(ListenerCommand_Action)(0),             // 0: bridge.ListenerCommand.Action
	(TunnelMessage_CommandType)(0),          // 1: bridge.TunnelMessage.CommandType
	(*ListenerStatus)(nil),                  // 2: bridge.ListenerStatus
	(*ListenerCommand)(nil),                 // 3: bridge.ListenerCommand
	(*BeaconMetadata)(nil),                  // 4: bridge.BeaconMetadata
	(*StageBeaconRequest)(nil),              // 5: bridge.StageBeaconRequest
	(*StageBeaconResponse)(nil),             // 6: bridge.StageBeaconResponse
	(*CheckInBeaconRequest)(nil),            // 7: bridge.CheckInBeaconRequest
	(*Task)(nil),                            // 8: bridge.Task
	(*CheckInBeaconResponse)(nil),           // 9: bridge.CheckInBeaconResponse
	(*PushBeaconOutputRequest)(nil),         // 10: bridge.PushBeaconOutputRequest
	(*PushBeaconOutputResponse)(nil),        // 11: bridge.PushBeaconOutputResponse
	(*GetListenerSharedSecretRequest)(nil),  // 12: bridge.GetListenerSharedSecretRequest
	(*GetListenerSharedSecretResponse)(nil), // 13: bridge.GetListenerSharedSecretResponse
	(*GetBeaconSessionKeyRequest)(nil),      // 14: bridge.GetBeaconSessionKeyRequest
	(*GetBeaconSessionKeyResponse)(nil),     // 15: bridge.GetBeaconSessionKeyResponse
	(*LogListenerEventRequest)(nil),         // 16: bridge.LogListenerEventRequest
	(*LogListenerEventResponse)(nil),        // 17: bridge.LogListenerEventResponse
	(*GetBeaconConfigRequest)(nil),          // 18: bridge.GetBeaconConfigRequest
	(*GetBeaconConfigResponse)(nil),         // 19: bridge.GetBeaconConfigResponse
	(*GetTaskedFileChunkRequest)(nil),       // 20: bridge.GetTaskedFileChunkRequest
	(*GetTaskedFileChunkResponse)(nil),      // 21: bridge.GetTaskedFileChunkResponse
	(*TunnelMessage)(nil),                   // 22: bridge.TunnelMessage
	nil,                                     // 23: bridge.LogListenerEventRequest.FieldsEntry
	nil,                                     // 24: bridge.GetBeaconConfigResponse.ConfigEntry
	(*timestamppb.Timestamp)(nil),           // 25: google.protobuf.Timestamp
}
var file_pkg_bridge_bridge_proto_depIdxs = []int32{
	0,  // 0: bridge.ListenerCommand.action:type_name -> bridge.ListenerCommand.Action
	25, // 1: bridge.StageBeaconRequest.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 2: bridge.StageBeaconRequest.metadata:type_name -> bridge.BeaconMetadata
	25, // 3: bridge.CheckInBeaconRequest.timestamp:type_name -> google.protobuf.Timestamp
	22, // 4: bridge.CheckInBeaconRequest.outgoing_tunnel_data:type_name -> bridge.TunnelMessage
	8,  // 5: bridge.CheckInBeaconResponse.tasks:type_name -> bridge.Task
	22, // 6: bridge.CheckInBeaconResponse.incoming_tunnel_data:type_name -> bridge.TunnelMessage
	25, // 7: bridge.PushBeaconOutputRequest.timestamp:type_name -> google.protobuf.Timestamp
	23, // 8: bridge.LogListenerEventRequest.fields:type_name -> bridge.LogListenerEventRequest.FieldsEntry
	24, // 9: bridge.GetBeaconConfigResponse.config:type_name -> bridge.GetBeaconConfigResponse.ConfigEntry
	1,  // 10: bridge.TunnelMessage.command_type:type_name -> bridge.TunnelMessage.CommandType
	5,  // 11: bridge.TeamServerBridgeService.StageBeacon:input_type -> bridge.StageBeaconRequest
	7,  // 12: bridge.TeamServerBridgeService.CheckInBeacon:input_type -> bridge.CheckInBeaconRequest
	10, // 13: bridge.TeamServerBridgeService.PushBeaconOutput:input_type -> bridge.PushBeaconOutputRequest
	12, // 14: bridge.TeamServerBridgeService.GetListenerSharedSecret:input_type -> bridge.GetListenerSharedSecretRequest
	14, // 15: bridge.TeamServerBridgeService.GetBeaconSessionKey:input_type -> bridge.GetBeaconSessionKeyRequest
	16, // 16: bridge.TeamServerBridgeService.LogListenerEvent:input_type -> bridge.LogListenerEventRequest
	18, // 17: bridge.TeamServerBridgeService.GetBeaconConfig:input_type -> bridge.GetBeaconConfigRequest
	20, // 18: bridge.TeamServerBridgeService.GetTaskedFileChunk:input_type -> bridge.GetTaskedFileChunkRequest
	2,  // 19: bridge.TeamServerBridgeService.ListenerControl:input_type -> bridge.ListenerStatus
	6,  // 20: bridge.TeamServerBridgeService.StageBeacon:output_type -> bridge.StageBeaconResponse
	9,  // 21: bridge.TeamServerBridgeService.CheckInBeacon:output_type -> bridge.CheckInBeaconResponse
	11, // 22: bridge.TeamServerBridgeService.PushBeaconOutput:output_type -> bridge.PushBeaconOutputResponse
	13, // 23: bridge.TeamServerBridgeService.GetListenerSharedSecret:output_type -> bridge.GetListenerSharedSecretResponse
	15, // 24: bridge.TeamServerBridgeService.GetBeaconSessionKey:output_type -> bridge.GetBeaconSessionKeyResponse
	17, // 25: bridge.TeamServerBridgeService.LogListenerEvent:output_type -> bridge.LogListenerEventResponse
	19, // 26: bridge.TeamServerBridgeService.GetBeaconConfig:output_type -> bridge.GetBeaconConfigResponse
	21, // 27: bridge.TeamServerBridgeService.GetTaskedFileChunk:output_type -> bridge.GetTaskedFileChunkResponse
	3,  // 28: bridge.TeamServerBridgeService.ListenerControl:output_type -> bridge.ListenerCommand
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_bridge_bridge_proto_init() }
func file_pkg_bridge_bridge_proto_init() {
	if File_pkg_bridge_bridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_bridge_bridge_proto_rawDesc), len(file_pkg_bridge_bridge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_bridge_bridge_proto_goTypes,
		DependencyIndexes: file_pkg_bridge_bridge_proto_depIdxs,
		EnumInfos:         file_pkg_bridge_bridge_proto_enumTypes,
		MessageInfos:      file_pkg_bridge_bridge_proto_msgTypes,
	}.Build()
	File_pkg_bridge_bridge_proto = out.File
	file_pkg_bridge_bridge_proto_goTypes = nil
	file_pkg_bridge_bridge_proto_depIdxs = nil
}
