// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.0
// source: pkg/bridge/bridge.proto

package bridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Beacon 的核心元数据
type BeaconMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeaconId        string `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`                         // Beacon 自身的 UUID 或唯一标识符
	Pid             int32  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`                                                  // 进程 ID
	Os              string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`                                                     // 操作系统类型 (e.g., "windows", "linux", "darwin")
	Arch            string `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`                                                 // CPU 架构 (e.g., "amd64", "arm64", "x86")
	Username        string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`                                         // 当前用户名
	Hostname        string `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`                                         // 主机名
	InternalIp      string `protobuf:"bytes,7,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`                   // 内部 IP 地址
	ProcessName     string `protobuf:"bytes,8,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`                // Beacon 进程名
	IsHighIntegrity bool   `protobuf:"varint,9,opt,name=is_high_integrity,json=isHighIntegrity,proto3" json:"is_high_integrity,omitempty"` // 是否在高权限下运行
}

func (x *BeaconMetadata) Reset() {
	*x = BeaconMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeaconMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconMetadata) ProtoMessage() {}

func (x *BeaconMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconMetadata.ProtoReflect.Descriptor instead.
func (*BeaconMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *BeaconMetadata) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *BeaconMetadata) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *BeaconMetadata) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *BeaconMetadata) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *BeaconMetadata) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BeaconMetadata) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *BeaconMetadata) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *BeaconMetadata) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *BeaconMetadata) GetIsHighIntegrity() bool {
	if x != nil {
		return x.IsHighIntegrity
	}
	return false
}

// Staging 请求
type StageBeaconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListenerName string                 `protobuf:"bytes,1,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"` // 处理此请求的 Listener 实例名
	RemoteAddr   string                 `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`       // Beacon 的来源网络地址
	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // Listener 接收到请求的时间戳
	Metadata     *BeaconMetadata        `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`                             // Listener 解析后的 Beacon 元数据
	PublicKey    []byte                 `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`          // 可选: Beacon 的公钥，用于加密 SessionKey
}

func (x *StageBeaconRequest) Reset() {
	*x = StageBeaconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageBeaconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageBeaconRequest) ProtoMessage() {}

func (x *StageBeaconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageBeaconRequest.ProtoReflect.Descriptor instead.
func (*StageBeaconRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *StageBeaconRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

func (x *StageBeaconRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *StageBeaconRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StageBeaconRequest) GetMetadata() *BeaconMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StageBeaconRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// Staging 响应
type StageBeaconResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignedBeaconId    string `protobuf:"bytes,1,opt,name=assigned_beacon_id,json=assignedBeaconId,proto3" json:"assigned_beacon_id,omitempty"`           // TeamServer 确认或分配的 ID
	SessionKey          []byte `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`                               // 分配的会话密钥 (可能是原始密钥或用 PublicKey 加密后的)
	SessionKeyEncrypted bool   `protobuf:"varint,3,opt,name=session_key_encrypted,json=sessionKeyEncrypted,proto3" json:"session_key_encrypted,omitempty"` // 指示 session_key 是否已被加密
}

func (x *StageBeaconResponse) Reset() {
	*x = StageBeaconResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageBeaconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageBeaconResponse) ProtoMessage() {}

func (x *StageBeaconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageBeaconResponse.ProtoReflect.Descriptor instead.
func (*StageBeaconResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *StageBeaconResponse) GetAssignedBeaconId() string {
	if x != nil {
		return x.AssignedBeaconId
	}
	return ""
}

func (x *StageBeaconResponse) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *StageBeaconResponse) GetSessionKeyEncrypted() bool {
	if x != nil {
		return x.SessionKeyEncrypted
	}
	return false
}

// CheckIn 请求
type CheckInBeaconRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeaconId     string                 `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`             // 进行心跳的 Beacon ID
	ListenerName string                 `protobuf:"bytes,2,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"` // 处理此请求的 Listener 实例名
	RemoteAddr   string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`       // Beacon 的来源网络地址
	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // Listener 接收到请求的时间戳
}

func (x *CheckInBeaconRequest) Reset() {
	*x = CheckInBeaconRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckInBeaconRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInBeaconRequest) ProtoMessage() {}

func (x *CheckInBeaconRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInBeaconRequest.ProtoReflect.Descriptor instead.
func (*CheckInBeaconRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *CheckInBeaconRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *CheckInBeaconRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

func (x *CheckInBeaconRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *CheckInBeaconRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Task 结构定义
type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId    string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`           // TeamServer 分配的任务唯一 ID
	CommandId uint32 `protobuf:"varint,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // 指令的操作码
	Arguments []byte `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`                   // 原始未加密参数 (TeamServer 内部格式)
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *Task) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// CheckIn 响应
type CheckInBeaconResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tasks    []*Task `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`                        // 原始未加密任务对象列表
	NewSleep int32   `protobuf:"varint,2,opt,name=new_sleep,json=newSleep,proto3" json:"new_sleep,omitempty"` // 可选: 新的 sleep 时间 (秒)
}

func (x *CheckInBeaconResponse) Reset() {
	*x = CheckInBeaconResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckInBeaconResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInBeaconResponse) ProtoMessage() {}

func (x *CheckInBeaconResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInBeaconResponse.ProtoReflect.Descriptor instead.
func (*CheckInBeaconResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *CheckInBeaconResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *CheckInBeaconResponse) GetNewSleep() int32 {
	if x != nil {
		return x.NewSleep
	}
	return 0
}

// PushOutput 请求
type PushBeaconOutputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeaconId     string                 `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`             // 回传结果的 Beacon ID
	ListenerName string                 `protobuf:"bytes,2,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"` // 处理此请求的 Listener 实例名
	RemoteAddr   string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`       // Beacon 的来源网络地址
	Timestamp    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                           // Listener 接收到请求的时间戳
	TaskId       string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                   // 此结果对应的任务 ID
	CommandId    uint32                 `protobuf:"varint,6,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`         // 执行的指令 ID
	Status       int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                // 任务执行状态码 (0 代表成功)
	Output       []byte                 `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty"`                                 // **已由 Listener 解密** 的原始任务输出数据 (TeamServer 内部格式)
	ErrorMessage string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 如果 status != 0，对应的错误信息
}

func (x *PushBeaconOutputRequest) Reset() {
	*x = PushBeaconOutputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushBeaconOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBeaconOutputRequest) ProtoMessage() {}

func (x *PushBeaconOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBeaconOutputRequest.ProtoReflect.Descriptor instead.
func (*PushBeaconOutputRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{6}
}

func (x *PushBeaconOutputRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

func (x *PushBeaconOutputRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

func (x *PushBeaconOutputRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *PushBeaconOutputRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PushBeaconOutputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PushBeaconOutputRequest) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *PushBeaconOutputRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PushBeaconOutputRequest) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *PushBeaconOutputRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// PushOutput 响应
type PushBeaconOutputResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushBeaconOutputResponse) Reset() {
	*x = PushBeaconOutputResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushBeaconOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBeaconOutputResponse) ProtoMessage() {}

func (x *PushBeaconOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBeaconOutputResponse.ProtoReflect.Descriptor instead.
func (*PushBeaconOutputResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{7}
}

// 获取 Listener SharedSecret 请求
type GetListenerSharedSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListenerName string `protobuf:"bytes,1,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
}

func (x *GetListenerSharedSecretRequest) Reset() {
	*x = GetListenerSharedSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListenerSharedSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerSharedSecretRequest) ProtoMessage() {}

func (x *GetListenerSharedSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerSharedSecretRequest.ProtoReflect.Descriptor instead.
func (*GetListenerSharedSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{8}
}

func (x *GetListenerSharedSecretRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

// 获取 Listener SharedSecret 响应
type GetListenerSharedSecretResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SharedSecret []byte `protobuf:"bytes,1,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
}

func (x *GetListenerSharedSecretResponse) Reset() {
	*x = GetListenerSharedSecretResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListenerSharedSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerSharedSecretResponse) ProtoMessage() {}

func (x *GetListenerSharedSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerSharedSecretResponse.ProtoReflect.Descriptor instead.
func (*GetListenerSharedSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{9}
}

func (x *GetListenerSharedSecretResponse) GetSharedSecret() []byte {
	if x != nil {
		return x.SharedSecret
	}
	return nil
}

// 获取 Beacon SessionKey 请求
type GetBeaconSessionKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeaconId string `protobuf:"bytes,1,opt,name=beacon_id,json=beaconId,proto3" json:"beacon_id,omitempty"`
}

func (x *GetBeaconSessionKeyRequest) Reset() {
	*x = GetBeaconSessionKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBeaconSessionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeaconSessionKeyRequest) ProtoMessage() {}

func (x *GetBeaconSessionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeaconSessionKeyRequest.ProtoReflect.Descriptor instead.
func (*GetBeaconSessionKeyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{10}
}

func (x *GetBeaconSessionKeyRequest) GetBeaconId() string {
	if x != nil {
		return x.BeaconId
	}
	return ""
}

// 获取 Beacon SessionKey 响应
type GetBeaconSessionKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionKey []byte `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Found      bool   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"` // Beacon 是否存在且活动
}

func (x *GetBeaconSessionKeyResponse) Reset() {
	*x = GetBeaconSessionKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBeaconSessionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeaconSessionKeyResponse) ProtoMessage() {}

func (x *GetBeaconSessionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeaconSessionKeyResponse.ProtoReflect.Descriptor instead.
func (*GetBeaconSessionKeyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{11}
}

func (x *GetBeaconSessionKeyResponse) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *GetBeaconSessionKeyResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// 记录 Listener 日志事件请求
type LogListenerEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListenerName string            `protobuf:"bytes,1,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
	Level        string            `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`                                                                                           // 日志级别 ("INFO", "WARN", "ERROR", "DEBUG")
	Message      string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                                       // 日志消息
	Fields       map[string]string `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 结构化日志字段
}

func (x *LogListenerEventRequest) Reset() {
	*x = LogListenerEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogListenerEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogListenerEventRequest) ProtoMessage() {}

func (x *LogListenerEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogListenerEventRequest.ProtoReflect.Descriptor instead.
func (*LogListenerEventRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{12}
}

func (x *LogListenerEventRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

func (x *LogListenerEventRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogListenerEventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogListenerEventRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 记录 Listener 日志事件响应
type LogListenerEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogListenerEventResponse) Reset() {
	*x = LogListenerEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogListenerEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogListenerEventResponse) ProtoMessage() {}

func (x *LogListenerEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogListenerEventResponse.ProtoReflect.Descriptor instead.
func (*LogListenerEventResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{13}
}

// 获取 Beacon 配置请求
type GetBeaconConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListenerName string `protobuf:"bytes,1,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
}

func (x *GetBeaconConfigRequest) Reset() {
	*x = GetBeaconConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBeaconConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeaconConfigRequest) ProtoMessage() {}

func (x *GetBeaconConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeaconConfigRequest.ProtoReflect.Descriptor instead.
func (*GetBeaconConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{14}
}

func (x *GetBeaconConfigRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

// 获取 Beacon 配置响应
type GetBeaconConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // Key-Value 配置对 (例如回连地址, 端口等)
}

func (x *GetBeaconConfigResponse) Reset() {
	*x = GetBeaconConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBeaconConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBeaconConfigResponse) ProtoMessage() {}

func (x *GetBeaconConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBeaconConfigResponse.ProtoReflect.Descriptor instead.
func (*GetBeaconConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{15}
}

func (x *GetBeaconConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// 获取文件分片请求
type GetTaskedFileChunkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId      string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                 // 'download' 任务的 ID
	ChunkNumber int32  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"` // 请求的分片序号 (从 0 开始)
}

func (x *GetTaskedFileChunkRequest) Reset() {
	*x = GetTaskedFileChunkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskedFileChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskedFileChunkRequest) ProtoMessage() {}

func (x *GetTaskedFileChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskedFileChunkRequest.ProtoReflect.Descriptor instead.
func (*GetTaskedFileChunkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{16}
}

func (x *GetTaskedFileChunkRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskedFileChunkRequest) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

// 获取文件分片响应
type GetTaskedFileChunkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkData []byte `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"` // 分片的二进制数据
}

func (x *GetTaskedFileChunkResponse) Reset() {
	*x = GetTaskedFileChunkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_bridge_bridge_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskedFileChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskedFileChunkResponse) ProtoMessage() {}

func (x *GetTaskedFileChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_bridge_bridge_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskedFileChunkResponse.ProtoReflect.Descriptor instead.
func (*GetTaskedFileChunkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_bridge_bridge_proto_rawDescGZIP(), []int{17}
}

func (x *GetTaskedFileChunkResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

var File_pkg_bridge_bridge_proto protoreflect.FileDescriptor

var file_pkg_bridge_bridge_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2f, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8b, 0x02, 0x0a, 0x0e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70,
	0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x70, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x70, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x68, 0x69, 0x67, 0x68, 0x5f, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69,
	0x73, 0x48, 0x69, 0x67, 0x68, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x69, 0x74, 0x79, 0x22, 0xe7,
	0x01, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x67, 0x65, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12, 0x38, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x32, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x98, 0x01, 0x0a, 0x13, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x12, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x62, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12,
	0x32, 0x0a, 0x15, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x42,
	0x65, 0x61, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5c, 0x0a, 0x04, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x58, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x49, 0x6e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x6c, 0x65, 0x65,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x53, 0x6c, 0x65, 0x65,
	0x70, 0x22, 0xc3, 0x02, 0x0a, 0x17, 0x50, 0x75, 0x73, 0x68, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61,
	0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x50, 0x75, 0x73, 0x68, 0x42,
	0x65, 0x61, 0x63, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x45, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x1f, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x22, 0x39, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x54, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x22, 0xee, 0x01, 0x0a, 0x17, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x4c, 0x6f,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x1a, 0x0a, 0x18, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x3d, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x99, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x57, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x3b, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x65,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74,
	0x61, 0x32, 0xda, 0x05, 0x0a, 0x17, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a,
	0x0b, 0x53, 0x74, 0x61, 0x67, 0x65, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x62,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x42, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e,
	0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x49, 0x6e, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x42, 0x65, 0x61, 0x63, 0x6f,
	0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1f, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x26, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x2e,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65,
	0x61, 0x63, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x1e, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x61,
	0x63, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x21, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x65, 0x64, 0x46, 0x69, 0x6c,
	0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15,
	0x5a, 0x13, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x63, 0x32, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_bridge_bridge_proto_rawDescOnce sync.Once
	file_pkg_bridge_bridge_proto_rawDescData = file_pkg_bridge_bridge_proto_rawDesc
)

func file_pkg_bridge_bridge_proto_rawDescGZIP() []byte {
	file_pkg_bridge_bridge_proto_rawDescOnce.Do(func() {
		file_pkg_bridge_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_bridge_bridge_proto_rawDescData)
	})
	return file_pkg_bridge_bridge_proto_rawDescData
}

var file_pkg_bridge_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pkg_bridge_bridge_proto_goTypes = []interface{}{
	(*BeaconMetadata)(nil),                  // 0: bridge.BeaconMetadata
	(*StageBeaconRequest)(nil),              // 1: bridge.StageBeaconRequest
	(*StageBeaconResponse)(nil),             // 2: bridge.StageBeaconResponse
	(*CheckInBeaconRequest)(nil),            // 3: bridge.CheckInBeaconRequest
	(*Task)(nil),                            // 4: bridge.Task
	(*CheckInBeaconResponse)(nil),           // 5: bridge.CheckInBeaconResponse
	(*PushBeaconOutputRequest)(nil),         // 6: bridge.PushBeaconOutputRequest
	(*PushBeaconOutputResponse)(nil),        // 7: bridge.PushBeaconOutputResponse
	(*GetListenerSharedSecretRequest)(nil),  // 8: bridge.GetListenerSharedSecretRequest
	(*GetListenerSharedSecretResponse)(nil), // 9: bridge.GetListenerSharedSecretResponse
	(*GetBeaconSessionKeyRequest)(nil),      // 10: bridge.GetBeaconSessionKeyRequest
	(*GetBeaconSessionKeyResponse)(nil),     // 11: bridge.GetBeaconSessionKeyResponse
	(*LogListenerEventRequest)(nil),         // 12: bridge.LogListenerEventRequest
	(*LogListenerEventResponse)(nil),        // 13: bridge.LogListenerEventResponse
	(*GetBeaconConfigRequest)(nil),          // 14: bridge.GetBeaconConfigRequest
	(*GetBeaconConfigResponse)(nil),         // 15: bridge.GetBeaconConfigResponse
	(*GetTaskedFileChunkRequest)(nil),       // 16: bridge.GetTaskedFileChunkRequest
	(*GetTaskedFileChunkResponse)(nil),      // 17: bridge.GetTaskedFileChunkResponse
	nil,                                     // 18: bridge.LogListenerEventRequest.FieldsEntry
	nil,                                     // 19: bridge.GetBeaconConfigResponse.ConfigEntry
	(*timestamppb.Timestamp)(nil),           // 20: google.protobuf.Timestamp
}
var file_pkg_bridge_bridge_proto_depIdxs = []int32{
	20, // 0: bridge.StageBeaconRequest.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: bridge.StageBeaconRequest.metadata:type_name -> bridge.BeaconMetadata
	20, // 2: bridge.CheckInBeaconRequest.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 3: bridge.CheckInBeaconResponse.tasks:type_name -> bridge.Task
	20, // 4: bridge.PushBeaconOutputRequest.timestamp:type_name -> google.protobuf.Timestamp
	18, // 5: bridge.LogListenerEventRequest.fields:type_name -> bridge.LogListenerEventRequest.FieldsEntry
	19, // 6: bridge.GetBeaconConfigResponse.config:type_name -> bridge.GetBeaconConfigResponse.ConfigEntry
	1,  // 7: bridge.TeamServerBridgeService.StageBeacon:input_type -> bridge.StageBeaconRequest
	3,  // 8: bridge.TeamServerBridgeService.CheckInBeacon:input_type -> bridge.CheckInBeaconRequest
	6,  // 9: bridge.TeamServerBridgeService.PushBeaconOutput:input_type -> bridge.PushBeaconOutputRequest
	8,  // 10: bridge.TeamServerBridgeService.GetListenerSharedSecret:input_type -> bridge.GetListenerSharedSecretRequest
	10, // 11: bridge.TeamServerBridgeService.GetBeaconSessionKey:input_type -> bridge.GetBeaconSessionKeyRequest
	12, // 12: bridge.TeamServerBridgeService.LogListenerEvent:input_type -> bridge.LogListenerEventRequest
	14, // 13: bridge.TeamServerBridgeService.GetBeaconConfig:input_type -> bridge.GetBeaconConfigRequest
	16, // 14: bridge.TeamServerBridgeService.GetTaskedFileChunk:input_type -> bridge.GetTaskedFileChunkRequest
	2,  // 15: bridge.TeamServerBridgeService.StageBeacon:output_type -> bridge.StageBeaconResponse
	5,  // 16: bridge.TeamServerBridgeService.CheckInBeacon:output_type -> bridge.CheckInBeaconResponse
	7,  // 17: bridge.TeamServerBridgeService.PushBeaconOutput:output_type -> bridge.PushBeaconOutputResponse
	9,  // 18: bridge.TeamServerBridgeService.GetListenerSharedSecret:output_type -> bridge.GetListenerSharedSecretResponse
	11, // 19: bridge.TeamServerBridgeService.GetBeaconSessionKey:output_type -> bridge.GetBeaconSessionKeyResponse
	13, // 20: bridge.TeamServerBridgeService.LogListenerEvent:output_type -> bridge.LogListenerEventResponse
	15, // 21: bridge.TeamServerBridgeService.GetBeaconConfig:output_type -> bridge.GetBeaconConfigResponse
	17, // 22: bridge.TeamServerBridgeService.GetTaskedFileChunk:output_type -> bridge.GetTaskedFileChunkResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_bridge_bridge_proto_init() }
func file_pkg_bridge_bridge_proto_init() {
	if File_pkg_bridge_bridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_bridge_bridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeaconMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageBeaconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageBeaconResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckInBeaconRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckInBeaconResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushBeaconOutputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushBeaconOutputResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListenerSharedSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListenerSharedSecretResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBeaconSessionKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBeaconSessionKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogListenerEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogListenerEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBeaconConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBeaconConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskedFileChunkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_bridge_bridge_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskedFileChunkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_bridge_bridge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_bridge_bridge_proto_goTypes,
		DependencyIndexes: file_pkg_bridge_bridge_proto_depIdxs,
		MessageInfos:      file_pkg_bridge_bridge_proto_msgTypes,
	}.Build()
	File_pkg_bridge_bridge_proto = out.File
	file_pkg_bridge_bridge_proto_rawDesc = nil
	file_pkg_bridge_bridge_proto_goTypes = nil
	file_pkg_bridge_bridge_proto_depIdxs = nil
}
